#!/usr/bin/csh

#  tar and gzip all files for a new GAMAP release
#
#  call: release_gamap VERSION
#
#  the result will be a gamap.VERSION.tar.gz file in ~/IDL


if ( $#argv == 0 ) then
   echo "usage:  release_gamap {VERSION}"
   echo "        VERSION: e.g. v2-01"
   exit(1)
endif

set curdir = `pwd`
cd ~/IDL

tar -cvf gamap.$1.tar tools/*.pro gamap/*.pro gamap/*.dat gamap/*.defaults tools/REVISIONS_TOOLS gamap/REVISIONS_GAMAP gamap/KNOWN_BUGS
gzip gamap.$1.tar

cd $curdir

echo Done.

