FUNCTION MAKEVECTOR, DATA

;+
; AUTHOR: ROKJIN J. PARK
; FUNCTION REVEC REFORMS 2 OR GREATER DIMENSIONAL ARRAYS INTO
; 1-D VECTOR 
;-

  DIM = SIZE(DATA,/DIM)
  L = 1L
  FOR N = 0, N_ELEMENTS(DIM)-1 DO L = L * DIM[N]

  RETURN, REFORM(DATA, L)
END
